### PR TITLE
Run Luacheck in Travis

### LINKED ISSUE #88: Run Luacheck in Travis
We should automate this to avoid merging code that fails luacheck.

### PR DESCRIPTION
**Pull request by ahmedkrmn**
Closes #88

### CODE REVIEW

**Comment by ahmedkrmn** [comment]
@hugomg Travis is failing because `luacheck` shows two warnings:

1. ```
    Checking spec/pallenec_spec.lua                   1 warning
        spec/pallenec_spec.lua:47:24: unused variable out
    ```
    This should be fixed when PR #146 is merged.

---

2. ```
    Checking pallene/to_ir.lua                        1 warning
        pallene/to_ir.lua:1:7: unused variable ast
    ```

**Comment by ahmedkrmn** [comment]
@hugomg what do you think should be done regarding the second warning?

**Comment by hugomg** [comment]
That one is also fixed in PR 146 :)

**Comment by ahmedkrmn** [comment]
> That one is also fixed in PR 146 :)

Ah OK, haven't noticed that you deleted this line `local ast = require "pallene.ast"` in your PR.

**Pull request merged**
