### PR TITLE
Standardize single quotation marks in checker error messages

### PR DESCRIPTION
**Pull request by ahmedkrmn**
Fixes issue #135.

### CODE REVIEW

**Comment by ahmedkrmn** [comment]
@hugomg and @gligneul I think Travis is failing because this commit changes the error messages, right ?!

**Comment by hugomg** [comment]
Thanks for your PR!

I think Travis is working fine in this case. The problem is that some of the unit tests inside the `spec` directory stopped passing after you changed the error messages. Those unit tests will also need to be updated to match the changes made.

To run the unit tests on your machine, install and run the busted tool, as described in the [Running the test suite](https://github.com/pallene-lang/pallene#running-the-test-suite) section of the README.

**Comment by ahmedkrmn** [comment]
@hugomg Done 👍

**Comment by ahmedkrmn** [comment]
@hugomg Done 👍

**Pull request merged**
